// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwX43GjOJZx1exlzNyo-8lhCAt_O24CrA',
    appId: '1:525357000777:web:6d1c9f2073b07dc985b798',
    messagingSenderId: '525357000777',
    projectId: 'inclass13-d48e7',
    authDomain: 'inclass13-d48e7.firebaseapp.com',
    storageBucket: 'inclass13-d48e7.firebasestorage.app',
    measurementId: 'G-LW362ZFL6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8xO_WE1x67K1KBiRNftEGPgAp0D3rq3w',
    appId: '1:525357000777:android:1624ac1a950fc0da85b798',
    messagingSenderId: '525357000777',
    projectId: 'inclass13-d48e7',
    storageBucket: 'inclass13-d48e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL2KQYXrhUZtXEPXI_TlaEFEiH_7eoBdA',
    appId: '1:525357000777:ios:ecf9afcf38fe1f9b85b798',
    messagingSenderId: '525357000777',
    projectId: 'inclass13-d48e7',
    storageBucket: 'inclass13-d48e7.firebasestorage.app',
    iosBundleId: 'com.example.inclass13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL2KQYXrhUZtXEPXI_TlaEFEiH_7eoBdA',
    appId: '1:525357000777:ios:ecf9afcf38fe1f9b85b798',
    messagingSenderId: '525357000777',
    projectId: 'inclass13-d48e7',
    storageBucket: 'inclass13-d48e7.firebasestorage.app',
    iosBundleId: 'com.example.inclass13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwX43GjOJZx1exlzNyo-8lhCAt_O24CrA',
    appId: '1:525357000777:web:aa1f6edc99557ee785b798',
    messagingSenderId: '525357000777',
    projectId: 'inclass13-d48e7',
    authDomain: 'inclass13-d48e7.firebaseapp.com',
    storageBucket: 'inclass13-d48e7.firebasestorage.app',
    measurementId: 'G-63PGNEGJ6M',
  );
}
